services:
    manager_db:
        image: mongo
        restart: always
        container_name: managerDB
        environment:
            MONGO_INITDB_ROOT_USERNAME: ${MONGO_ROOT_USERNAME}
            MONGO_INITDB_ROOT_PASSWORD: ${MONGO_ROOT_PASSWORD}
            MONGO_INITDB_USER_USERNAME: ${MONGO_USER_USERNAME}
            MONGO_INITDB_USER_PASSWORD: ${MONGO_USER_PASSWORD}
            MONGO_INITDB_DATABASE: ${MONGO_DATABASE}
        ports:
            - 27021:27017
        volumes:
            - ./data/mongo:/data/db
            - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js

    manager_web:
        image: node:hydrogen-slim
        container_name: manager
        command: /bin/sh -c "cd /srv/app && npm install && npm run dev"
        ports:
            - 4100:3000
        working_dir: /srv/app
        volumes:
            - type: bind
              source: ./
              target: /srv/app
            - /var/run/docker.sock:/var/run/docker.sock:ro
        tty: true
