import type { Metadata } from 'next';
import type { Session } from 'next-auth';
import { Manrope } from 'next/font/google';
import '@/styles/globals.css';
import { SessionProvider } from '@/components/session-provider';

const manrope = Manrope({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

type RootLayoutProps = {
	children: React.ReactNode;
	session?: Session;
};

export default function RootLayout({ children, session }: RootLayoutProps) {
	return (
		<html lang="en" suppressHydrationWarning>
			<head />
			<body className={manrope.className}>
				<SessionProvider session={session}>{children}</SessionProvider>
			</body>
		</html>
	);
}
